import fs from "fs";

// Define ranges and options
const locations = ["1", "2", "3", "4", "5"];
const bedroomsOptions = [1, 2, 3, 4];
const houseTypes = [1, 2, 3];
const featuresOptions = [3, 4, 5];
const agentPrefixes = ["071", "072", "073"];
const actionsOptions = ["for sale", "for rent", "for sale and rent"];

// Function to generate dummy Kenyan phone numbers
function generateAgentNumber() {
  const prefix =
    agentPrefixes[Math.floor(Math.random() * agentPrefixes.length)];
  const suffix = Math.floor(1000000 + Math.random() * 9000000); // Generates a 7-digit random number
  return prefix + suffix.toString().substring(1); // Ensures 7 digits after prefix
}

function generateName() {
  const names = [
    "Jamu Courts",
    "Golden Oak Residency",
    "Pineview Estates",
    "Meadowbrook Manor",
    "Riverfront Retreat",
    "Maplewood Heights",
    "Sunnyvale Villas",
    "Willowbrook Gardens",
    "Cedar Ridge Apartments",
    "Oakridge Meadows",
    "Lakeview Terrace",
    "Hillcrest Heights",
    "Whispering Pines",
    "Riverside Retreat",
    "Sunset Ridge Condos",
    "Greenwood Acres",
    "Fairview Heights",
    "Woodland Estates",
    "Mountain View Condos",
    "Pleasant Valley Homes",
    "Oceanview Apartments",
    "Lakeside Residences",
    "Highland Park Villas",
    "Valley Vista Homes",
    "Bayside Manor",
    "Ridgecrest Apartments",
    "Parkside Plaza",
    "Sycamore Springs",
    "Countryside Cottages",
    "Harborview Condos",
    "Silver Creek Apartments",
    "Brookside Bungalows",
    "Meadowview Heights",
    "Springfield Estates",
    "Oakhill Manor",
    "Bayview Towers",
    "Rustic Ridge Retreat",
    "Summerfield Condos",
    "Hilltop Haven",
    "Whitewater Apartments",
    "Forest Grove Estates",
    "Maple Leaf Residences",
    "Riverside Plaza",
    "Crescent Court",
    "Lighthouse Landing",
    "Seaview Residences",
    "Lakeshore Villas",
    "Stonebridge Estates",
    "Sunnyside Gardens",
    "Birchwood Bungalows",
    "Cherrywood Manor",
    "Park Place Condos",
    "Waterfront Retreat",
    "Timberline Terrace",
    "Palm Grove Apartments",
    "Serenity Springs",
    "Marina View Homes",
    "Wildwood Villas",
    "Cottage Cove",
    "Arbor Heights",
    "Golden Gate Residences",
    "Sunrise Meadows",
    "Mountain Crest Condos",
    "Harmony Hills",
    "Peachtree Place",
    "Silverlake Estates",
    "Vineyard Valley",
    "Cascade Heights",
    "Riverbend Retreat",
    "Evergreen Gardens",
    "Fairfield Apartments",
    "Glenwood Glen",
    "Ocean Breeze Villas",
    "Riverview Residences",
    "Shady Oaks Condos",
    "Parkview Plaza",
    "Lakewood Lodge",
    "Pinecrest Pointe",
    "Misty Meadows",
    "Hillcrest Heights",
    "Oakwood Overlook",
    "Cedar Creek Apartments",
    "Willowbrook Wharf",
    "Creekside Cottages",
    "Briarwood Bend",
    "Sagebrush Springs",
    "Lakeside Landing",
    "Woodland Walk",
    "Mountain View Manor",
    "Magnolia Meadows",
    "Summit View Condos",
    "Pondside Place",
    "Silver Springs Apartments",
    "Harbor Heights",
    "Cottonwood Court",
    "Valley View Villas",
    "Sunset Shores",
    "Ridgeview Residences",
    "Riverwalk Retreat",
    "Whispering Woods",
    "Sunnyside Springs",
    "Highland Hideaway",
    "Meadowview Mews",
    "Pinehurst Park",
    "Crestview Condos",
    "Evergreen Estates",
    "Fairway Meadows",
    "Parkside Place",
    "Woodland Way",
    "Mountain Crest Manor",
    "Sycamore Square",
    "Harbor View Haven",
    "Lakefront Landing",
    "Sunrise Square",
    "Bayside Breezes",
    "Silverton Springs",
    "Hillcrest Haven",
    "Riverside Ridge",
    "Ocean Oaks",
    "Meadowlark Manor",
    "Maplewood Manor",
    "Sunnyvale Springs",
    "Birchwood Bend",
    "Cedar Ridge Condos",
    "Willow Creek Apartments",
    "Lakewood Lane",
    "Pinegrove Plaza",
    "Misty Mountain Meadows",
    "Riverbend Ranch",
    "Serenity Shores",
    "Wildflower Walk",
    "Springfield Square",
    "Lakeview Lodge",
    "Fairview Falls",
    "Glenwood Gardens",
    "Woodland Waters",
    "Mountainview Manor",
    "Whitewater Wharf",
    "Creekside Cove",
    "Briarwood Bungalows",
    "Sagebrush Springs",
    "Lakeside Lagoon",
    "Valley Vista Villas",
    "Sunset Springs",
    "Ridgecrest Residences",
    "Riverwalk Ridge",
    "Whispering Willow",
    "Sunnyside Sanctuary",
    "Highland Hideaway",
    "Meadowview Mews",
    "Pinehurst Park",
    "Crestview Condos",
    "Evergreen Estates",
    "Fairway Meadows",
    "Parkside Place",
    "Woodland Way",
    "Mountain Crest Manor",
    "Sycamore Square",
    "Harbor View Haven",
    "Lakefront Landing",
    "Sunrise Square",
    "Bayside Breezes",
    "Silverton Springs",
    "Hillcrest Haven",
    "Riverside Ridge",
    "Ocean Oaks",
    "Meadowlark Manor",
    "Maplewood Manor",
    "Sunnyvale Springs",
    "Birchwood Bend",
    "Cedar Ridge Condos",
    "Willow Creek Apartments",
    "Lakewood Lane",
    "Pinegrove Plaza",
    "Misty Mountain Meadows",
    "Riverbend Ranch",
    "Serenity Shores",
    "Wildflower Walk",
    "Springfield Square",
    "Lakeview Lodge",
    "Fairview Falls",
    "Glenwood Gardens",
    "Woodland Waters",
    "Mountainview Manor",
    "Whitewater Wharf",
    "Creekside Cove",
    "Briarwood Bungalows",
    "Sagebrush Springs",
    "Lakeside Lagoon",
    "Valley Vista Villas",
    "Sunset Springs",
    "Ridgecrest Residences",
    "Riverwalk Ridge",
    "Whispering Willow",
    "Sunnyside Sanctuary",
    "Highland Hideaway",
    "Meadowview Mews",
    "Pinehurst Park",
    "Crestview Condos",
    "Evergreen Estates",
    "Fairway Meadows",
    "Parkside Place",
    "Woodland Way",
    "Mountain Crest Manor",
    "Sycamore Square",
    "Harbor View Haven",
    "Lakefront Landing",
    "Sunrise Square",
    "Bayside Breezes",
    "Silverton Springs",
    "Hillcrest Haven",
    "Riverside Ridge",
    "Ocean Oaks",
    "Meadowlark Manor",
    "Maplewood Manor",
    "Sunnyvale Springs",
    "Birchwood Bend",
    "Cedar Ridge Condos",
    "Willow Creek Apartments",
    "Lakewood Lane",
    "Pinegrove Plaza",
    "Misty Mountain Meadows",
    "Riverbend Ranch",
    "Serenity Shores",
    "Wildflower Walk",
    "Springfield Square",
    "Lakeview Lodge",
    "Fairview Falls",
    "Glenwood Gardens",
    "Woodland Waters",
    "Mountainview Manor",
    "Whitewater Wharf",
    "Creekside Cove",
    "Briarwood Bungalows",
    "Sagebrush Springs",
    "Lakeside Lagoon",
    "Valley Vista Villas",
    "Sunset Springs",
    "Ridgecrest Residences",
    "Riverwalk Ridge",
    "Whispering Willow",
    "Sunnyside Sanctuary",
    "Highland Hideaway",
    "Meadowview Mews",
    "Pinehurst Park",
    "Crestview Condos",
    "Evergreen Estates",
    "Fairway Meadows",
    "Parkside Place",
    "Woodland Way",
    "Mountain Crest Manor",
    "Sycamore Square",
    "Harbor View Haven",
    "Lakefront Landing",
    "Sunrise Square",
    "Bayside Breezes",
    "Silverton Springs",
    "Hillcrest Haven",
    "Riverside Ridge",
    "Ocean Oaks",
    "Meadowlark Manor",
    "Maplewood Manor",
    "Sunnyvale Springs",
    "Birchwood Bend",
    "Cedar Ridge Condos",
    "Willow Creek Apartments",
    "Lakewood Lane",
    "Pinegrove Plaza",
    "Misty Mountain Meadows",
    "Riverbend Ranch",
    "Serenity Shores",
    "Wildflower Walk",
    "Springfield Square",
    "Lakeview Lodge",
    "Fairview Falls",
    "Glenwood Gardens",
    "Woodland Waters",
    "Mountainview Manor",
    "Whitewater Wharf",
    "Creekside Cove",
    "Briarwood Bungalows",
    "Sagebrush Springs",
    "Lakeside Lagoon",
    "Valley Vista Villas",
    "Sunset Springs",
    "Ridgecrest Residences",
    "Riverwalk Ridge",
    "Whispering Willow",
    "Sunnyside Sanctuary",
    "Highland Hideaway",
    "Meadowview Mews",
    "Pinehurst Park",
    "Crestview Condos",
    "Evergreen Estates",
    "Fairway Meadows",
    "Parkside Place",
    "Woodland Way",
    "Mountain Crest Manor",
    "Sycamore Square",
    "Harbor View Haven",
    "Lakefront Landing",
    "Sunrise Square",
    "Bayside Breezes",
    "Silverton Springs",
    "Hillcrest Haven",
    "Riverside Ridge",
    "Ocean Oaks",
    "Meadowlark Manor",
    "Maplewood Manor",
    "Sunnyvale Springs",
    "Birchwood Bend",
    "Cedar Ridge Condos",
    "Willow Creek Apartments",
    "Lakewood Lane",
    "Pinegrove Plaza",
    "Misty Mountain Meadows",
    "Riverbend Ranch",
    "Serenity Shores",
    "Wildflower Walk",
    "Springfield Square",
    "Lakeview Lodge",
    "Fairview Falls",
    "Glenwood Gardens",
    "Woodland Waters",
    "Mountainview Manor",
    "Whitewater Wharf",
    "Creekside Cove",
    "Briarwood Bungalows",
    "Sagebrush Springs",
    "Lakeside Lagoon",
    "Valley Vista Villas",
    "Sunset Springs",
    "Ridgecrest Residences",
    "Riverwalk Ridge",
    "Whispering Willow",
    "Sunnyside Sanctuary",
    "Highland Hideaway",
    "Meadowview Mews",
    "Pinehurst Park",
    "Crestview Condos",
    "Evergreen Estates",
    "Fairway Meadows",
    "Parkside Place",
    "Woodland Way",
    "Mountain Crest Manor",
    "Sycamore Square",
    "Harbor View Haven",
    "Lakefront Landing",
    "Sunrise Square",
    "Bayside Breezes",
    "Silverton Springs",
    "Hillcrest Haven",
    "Riverside Ridge",
    "Ocean Oaks",
    "Meadowlark Manor",
    "Maplewood Manor",
    "Sunnyvale Springs",
    "Birchwood Bend",
    "Cedar Ridge Condos",
    "Willow Creek Apartments",
    "Lakewood Lane",
    "Pinegrove Plaza",
    "Misty Mountain Meadows",
    "Riverbend Ranch",
    "Serenity Shores",
    "Wildflower Walk",
    "Springfield Square",
    "Lakeview Lodge",
    "Fairview Falls",
    "Glenwood Gardens",
    "Woodland Waters",
    "Mountainview Manor",
    "Whitewater Wharf",
    "Creekside Cove",
    "Briarwood Bungalows",
    "Sagebrush Springs",
    "Lakeside Lagoon",
    "Valley Vista Villas",
    "Sunset Springs",
    "Ridgecrest Residences",
    "Riverwalk Ridge",
    "Whispering Willow",
    "Sunnyside Sanctuary",
    "Highland Hideaway",
    "Meadowview Mews",
    "Pinehurst Park",
    "Crestview Condos",
    "Evergreen Estates",
    "Fairway Meadows",
    "Parkside Place",
    "Woodland Way",
    "Mountain Crest Manor",
    "Sycamore Square",
    "Harbor View Haven",
    "Lakefront Landing",
    "Sunrise Square",
    "Bayside Breezes",
    "Silverton Springs",
    "Hillcrest Haven",
    "Riverside Ridge",
    "Ocean Oaks",
    "Meadowlark Manor",
    "Maplewood Manor",
    "Sunnyvale Springs",
    "Birchwood Bend",
    "Cedar Ridge Condos",
    "Willow Creek Apartments",
    "Lakewood Lane",
    "Pinegrove Plaza",
    "Misty Mountain Meadows",
    "Riverbend Ranch",
    "Serenity Shores",
    "Wildflower Walk",
    "Springfield Square",
    "Lakeview Lodge",
    "Fairview Falls",
    "Glenwood Gardens",
    "Woodland Waters",
    "Mountainview Manor",
    "Whitewater Wharf",
    "Creekside Cove",
    "Briarwood Bungalows",
    "Sagebrush Springs",
    "Lakeside Lagoon",
    "Valley Vista Villas",
    "Sunset Springs",
    "Ridgecrest Residences",
    "Riverwalk Ridge",
    "Whispering Willow",
    "Sunnyside Sanctuary",
    "Highland Hideaway",
    "Meadowview Mews",
    "Pinehurst Park",
    "Crestview Condos",
    "Evergreen Estates",
    "Fairway Meadows",
    "Parkside Place",
    "Woodland Way",
    "Mountain Crest Manor",
    "Sycamore Square",
    "Harbor View Haven",
    "Lakefront Landing",
    "Sunrise Square",
    "Bayside Breezes",
    "Silverton Springs",
    "Hillcrest Haven",
    "Riverside Ridge",
    "Ocean Oaks",
    "Meadowlark Manor",
    "Maplewood Manor",
    "Sunnyvale Springs",
    "Birchwood Bend",
    "Cedar Ridge Condos",
    "Willow Creek Apartments",
    "Lakewood Lane",
    "Pinegrove Plaza",
    "Misty Mountain Meadows",
    "Riverbend Ranch",
    "Serenity Shores",
    "Wildflower Walk",
    "Springfield Square",
    "Lakeview Lodge",
    "Fairview Falls",
    "Glenwood Gardens",
    "Woodland Waters",
    "Mountainview Manor",
    "Whitewater Wharf",
    "Creekside Cove",
    "Briarwood Bungalows",
    "Sagebrush Springs",
    "Lakeside Lagoon",
    "Valley Vista Villas",
    "Sunset Springs",
    "Ridgecrest Residences",
    "Riverwalk Ridge",
    "Whispering Willow",
    "Sunnyside Sanctuary",
    "Highland Hideaway",
    "Meadowview Mews",
    "Pinehurst Park",
    "Crestview Condos",
    "Evergreen Estates",
    "Fairway Meadows",
    "Parkside Place",
    "Woodland Way",
    "Mountain Crest Manor",
    "Sycamore Square",
    "Harbor View Haven",
    "Lakefront Landing",
    "Sunrise Square",
    "Bayside Breezes",
    "Silverton Springs",
    "Hillcrest Haven",
    "Riverside Ridge",
    "Ocean Oaks",
    "Meadowlark Manor",
    "Maplewood Manor",
    "Sunnyvale Springs",
    "Birchwood Bend",
    "Cedar Ridge Condos",
    "Willow Creek Apartments",
    "Lakewood Lane",
    "Pinegrove Plaza",
    "Misty Mountain Meadows",
    "Riverbend Ranch",
    "Serenity Shores",
    "Wildflower Walk",
    "Springfield Square",
    "Lakeview Lodge",
    "Fairview Falls",
    "Glenwood Gardens",
    "Woodland Waters",
    "Mountainview Manor",
    "Whitewater Wharf",
    "Creekside Cove",
    "Briarwood Bungalows",
    "Sagebrush Springs",
    "Lakeside Lagoon",
    "Valley Vista Villas",
    "Sunset Springs",
    "Ridgecrest Residences",
    "Riverwalk Ridge",
    "Whispering Willow",
    "Sunnyside Sanctuary",
    "Highland Hideaway",
    "Meadowview Mews",
    "Pinehurst Park",
    "Crestview Condos",
    "Evergreen Estates",
    "Fairway Meadows",
    "Parkside Place",
    "Woodland Way",
    "Mountain Crest Manor",
    "Sycamore Square",
    "Harbor View Haven",
    "Lakefront Landing",
    "Sunrise Square",
    "Bayside Breezes",
    "Silverton Springs",
    "Hillcrest Haven",
    "Riverside Ridge",
    "Ocean Oaks",
    "Meadowlark Manor",
    "Maplewood Manor",
    "Sunnyvale Springs",
    "Birchwood Bend",
    "Cedar Ridge Condos",
    "Willow Creek Apartments",
    "Lakewood Lane",
    "Pinegrove Plaza",
    "Misty Mountain Meadows",
    "Riverbend Ranch",
    "Serenity Shores",
    "Wildflower Walk",
    "Springfield Square",
    "Lakeview Lodge",
    "Fairview Falls",
    "Glenwood Gardens",
    "Woodland Waters",
    "Mountainview Manor",
    "Whitewater Wharf",
    "Creekside Cove",
    "Briarwood Bungalows",
    "Sagebrush Springs",
    "Lakeside Lagoon",
    "Valley Vista Villas",
    "Sunset Springs",
    "Ridge",
  ];

  return names[Math.floor(Math.random() * names.length)];
}

function generateDescription() {
  const descriptions = [
    "A charming property with modern amenities.",
    "An elegant residence offering breathtaking views.",
    "A cozy home nestled in a serene neighborhood.",
    "A luxurious estate perfect for entertaining guests.",
    "A spacious retreat with beautiful landscaping.",
    "A contemporary apartment with stylish interiors.",
    "An inviting family home with plenty of natural light.",
    "A tranquil sanctuary away from the hustle and bustle.",
    "A classic villa with timeless elegance.",
    "A modern townhouse designed for comfortable living.",
    "A picturesque property surrounded by lush greenery.",
    "A quaint cottage with rustic charm.",
    "A sophisticated penthouse with panoramic city views.",
    "A serene oasis with a private pool and spa.",
    "A chic loft in the heart of the city.",
    "A countryside estate with rolling hills and vineyards.",
    "An exclusive waterfront property with dock access.",
    "A character-filled bungalow with period features.",
    "A contemporary condo overlooking the city skyline.",
    "A secluded hideaway nestled among towering trees.",
    "A cozy cabin with a wood-burning fireplace.",
    "An architecturally designed home with open-plan living.",
    "A historic mansion steeped in grandeur and history.",
    "A beachfront villa with sweeping ocean views.",
    "A sun-drenched property with expansive outdoor entertaining areas.",
    "A modern duplex with sleek finishes and designer flair.",
    "A tranquil lakeside retreat with private beach access.",
    "A stylish urban apartment in a vibrant neighborhood.",
    "A charming farmhouse with a wraparound porch.",
    "An eco-friendly home with sustainable design features.",
    "A contemporary villa with indoor-outdoor flow.",
    "A mountain chalet with ski-in, ski-out access.",
    "A tropical paradise with lush gardens and waterfall features.",
    "A minimalist retreat with clean lines and minimalist decor.",
    "A heritage-listed property with period charm and elegance.",
    "A riverside cottage with a cozy fireplace and river views.",
    "A modernist masterpiece with floor-to-ceiling windows.",
    "A cozy townhome with a private courtyard.",
    "A luxury penthouse with a rooftop terrace and city skyline views.",
    "A tranquil farmstead with rolling pastures and grazing animals.",
    "A vineyard estate with award-winning wines and stunning vistas.",
    "A contemporary beach house with surf-side appeal.",
    "An artist's retreat with inspiring views and natural light.",
    "A historic brownstone with original architectural details.",
    "A secluded cabin with panoramic mountain views.",
    "A contemporary ranch-style home with outdoor living spaces.",
    "A lakeside lodge with rustic charm and modern comforts.",
    "A city loft with industrial chic design elements.",
    "A Tuscan-inspired villa with Mediterranean charm.",
    "A hilltop estate with commanding views of the countryside.",
    "A modernist townhouse with sleek, minimalist interiors.",
    "A colonial-style home with timeless elegance and grace.",
    "A beachside bungalow with ocean breezes and sandy shores.",
    "An architectural gem with unique design features.",
    "A rural retreat with vast acreage and natural beauty.",
    "A cozy cottage nestled in the heart of wine country.",
    "A contemporary oasis with lush landscaping and water features.",
    "A modern farmhouse with barn-style architecture.",
    "A penthouse retreat with floor-to-ceiling windows and skyline views.",
    "A coastal getaway with panoramic views of the sea.",
    "A stylish apartment with designer finishes and city views.",
    "A country estate with sprawling gardens and manicured lawns.",
    "A modern sanctuary with sleek lines and minimalist decor.",
    "A luxury chalet with ski-in, ski-out access to the slopes.",
    "A historic manor with period details and grand architecture.",
    "A lakeside retreat with private dock and boathouse.",
    "A contemporary beachfront villa with infinity pool and ocean views.",
    "A rustic cabin with a wood-burning fireplace and mountain vistas.",
    "An urban oasis with rooftop gardens and city skyline views.",
    "A Tuscan farmhouse with vineyard and olive grove.",
    "A secluded sanctuary with forested trails and wildlife.",
    "A modern townhouse with rooftop terrace and city views.",
    "A beachfront retreat with panoramic ocean views.",
    "A mountain hideaway with sweeping views of the valley below.",
    "A contemporary condo with luxury amenities and downtown location.",
    "A colonial-style residence with expansive verandas and lush gardens.",
    "A tranquil riverside cottage with fishing and boating amenities.",
    "A modernist masterpiece with cutting-edge design and technology.",
    "A countryside estate with equestrian facilities and rolling hills.",
    "A chic urban loft with industrial-chic design elements.",
    "A Mediterranean-inspired villa with panoramic sea views.",
    "A hillside retreat with infinity pool and sunset vistas.",
    "A historic farmhouse with period charm and modern comforts.",
    "A coastal cottage with panoramic views of the ocean.",
    "A modernist townhouse with clean lines and minimalist interiors.",
    "An idyllic retreat with private beach access and lush landscaping.",
    "A contemporary penthouse with sweeping city views and luxury amenities.",
    "A rustic cabin with stone fireplace and mountain views.",
    "An urban oasis with rooftop gardens and city skyline views.",
    "A Tuscan villa with vineyard and olive grove.",
    "A secluded sanctuary with forested trails and wildlife.",
    "A modern townhouse with rooftop terrace and city views.",
    "A beachfront retreat with panoramic ocean views.",
    "A mountain hideaway with sweeping views of the valley below.",
    "A contemporary condo with luxury amenities and downtown location.",
    "A colonial-style residence with expansive verandas and lush gardens.",
    "A tranquil riverside cottage with fishing and boating amenities.",
    "A modernist masterpiece with cutting-edge design and technology.",
    "A countryside estate with equestrian facilities and rolling hills.",
    "A chic urban loft with industrial-chic design elements.",
    "A Mediterranean-inspired villa with panoramic sea views.",
    "A hillside retreat with infinity pool and sunset vistas.",
    "A historic farmhouse with period charm and modern comforts.",
    "A coastal cottage with panoramic views of the ocean.",
    "A modernist townhouse with clean lines and minimalist interiors.",
    "An idyllic retreat with private beach access and lush landscaping.",
    "A contemporary penthouse with sweeping city views and luxury amenities.",
    "A rustic cabin with stone fireplace and mountain views.",
  ];

  return descriptions[Math.floor(Math.random() * descriptions.length)];
}

// Generate 60 records
const newRecords = [];
for (let i = 0; i < 60; i++) {
  const record = {
    name: generateName(),
    price: (
      Math.floor(Math.random() * (30000000 - 500000 + 1)) + 500000
    ).toLocaleString(), // Adjusted max price to 30,000,000
    description: generateDescription(),
    images: ["image1.jpg", "image2.jpg", "image3.jpg"],
    location: locations[Math.floor(Math.random() * locations.length)],
    bedrooms:
      bedroomsOptions[Math.floor(Math.random() * bedroomsOptions.length)],
    houseType: houseTypes[Math.floor(Math.random() * houseTypes.length)],
    features:
      featuresOptions[Math.floor(Math.random() * featuresOptions.length)],
    agent: generateAgentNumber(),
    actions: actionsOptions[Math.floor(Math.random() * actionsOptions.length)],
  };
  newRecords.push(record);
}

// Combine existing data with new records
const existingData = [
  // Your existing data goes here
];

const combinedData = existingData.concat(newRecords);

// Convert combinedData to JSON
const jsonData = JSON.stringify(combinedData, null, 2);

// Write JSON data to a file
fs.writeFile("properties.json", jsonData, (err) => {
  if (err) {
    console.error("Error writing file:", err);
    return;
  }
  console.log("Data has been written to properties.json");
});
